name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
      env:
        REACT_APP_USER_ID: ${{ secrets.REACT_APP_USER_ID }}
        REACT_APP_SERVICE_ID: ${{ secrets.REACT_APP_SERVICE_ID }}
        REACT_APP_TEMPLATE_ID: ${{ secrets.REACT_APP_TEMPLATE_ID }}
